version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./axum
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    # environment:
    #   REDIS_URL: redis://redis:6379
    env_file:
      - axum/.env
    volumes:
      - ./axum/posts.db:/app/posts.db

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
