version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  db:
    image: pgvector/pgvector:0.8.0-pg16
    container_name: neural_notes_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neural_notes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d neural_notes"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./axum
      dockerfile: Dockerfile.dev   # 개발용 Dockerfile 사용
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - axum/.env
    volumes:
      - ./axum:/app       # 전체 소스코드 마운트

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile.dev   # 개발용 Dockerfile 사용
    ports:
      - "5173:5173"
    volumes:
      - ./react:/app               # 전체 소스코드 마운트
    command: ["npm", "run", "dev", "--", "--host"]   # Vite dev 서버 핫리로드

  embed_api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi:/app
      - ~/.cache/huggingface:/home/appuser/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/home/appuser/.cache/huggingface
volumes:
  postgres_data:
