version: "3.9"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  db:
    image: postgres:16
    container_name: neural_notes_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neural_notes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d neural_notes"]
      interval: 5s
      timeout: 3s
      retries: 5


  backend:
    build:
      context: ./axum
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    # environment:
    #   REDIS_URL: redis://redis:6379
    env_file:
      - axum/.env
    volumes:
      - ./axum/posts.db:/app/posts.db

  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    # depends_on:
    #   - backend

  embed_api:
    build: ./fastapi
    ports:
      - "8001:8001"
volumes:
  postgres_data: