apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: neural-notes-axum:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              hostPort: 3000
          env:
            - name: JWT_SECRET
              value: "testsecrettestsecrettestsecrettestsecret"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: DATABASE_HOST
              value: "postgres"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "user"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "neural_notes"
            - name: EMBED_API_URL
              value: "http://embed-api:8001"
