name: CD FastAPI

on:
  push:
    branches:
      - master
    paths:
      - 'fastapi/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fastapi

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fly Auth
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy FastAPI App
        run: flyctl deploy --remote-only --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
