name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./axum
    steps:
      - uses: actions/checkout@v4

      - name: Format Check (cargo fmt)
        run: cargo fmt --all -- --check

      # - name: Lint Check (cargo clippy)
      #   run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Tests
        run: cargo test

      # - name: Docker Build
      #   run: docker build -t axum:ci .

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./react
    steps:
      - uses: actions/checkout@v4

      # - name: Docker Build
      #   run: docker build -t react:ci .